name: Build and release Go code

on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: 'go-project'
      go-version:
        required: false
        type: string
        default: '1.23'

jobs:
  version:
    uses: LarsNieuwenhuizen/workflows/.github/workflows/define-version.yml@feat/go-build-release-workflow
