name: Define next version of your application

on:
  workflow_call:
    outputs:
      release_version:
        description: "The next version of your application"
        value: ${{ jobs.version.outputs.release_version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.version.outputs.release_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Define version
        id: version
        uses: LarsNieuwenhuizen/action-define-release-version@v1

      - name: Set output
        run: echo "release_version=${{ steps.version.outputs.release_version }}" >> $GITHUB_OUTPUT
