name: Define next version of your application

on:
  workflow_call:
    outputs:
      release-version:
        description: "The next version of your application"
        value: ${{ jobs.version.outputs.release-version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.result.outputs.release-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Define version
        id: version
        uses: LarsNieuwenhuizen/action-define-release-version@v1

      - name: Set output
        id: result
        run: echo "release-version=${{ steps.version.outputs.release-version }}" >> $GITHUB_OUTPUT
