name: Generate sbom and cyclonedx with trivy for image

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      format:
        description: "format (table,json,template,sarif,cyclonedx,spdx,spdx-json,github,cosign-vuln) - Give comma separated to create multiple files"
        type: string
        default: spdx-json
      add-cyclonedx:
        required: true
        type: boolean
        default: false
      publish:
        required: true
        type: boolean
        default: true

env:
  TRIVY_VERSION: v0.59.1

jobs:
  create-format-matrix:
    runs-on: ubuntu-latest
    outputs:
      formats: ${{ steps.format-list.outputs.formats }}

    steps:
    - name: Create format array
      id: format-list
      run: |
        IFS=',' read -r -a array <<< "${{ inputs.format }}"
        result=$(printf '%s\n' "${array[@]}" | jq -R . | jq -s .)
        echo "formats=$result" >> "$GITHUB_OUTPUT"

  check-matrix:
    needs: create-format-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        format: ${{ fromJson(needs.create-format-matrix.outputs.formats) }}
    steps:
      - name: Check format
        run: |
          echo ${{ matrix.format }}

  generate-sbom:
    if: inputs.image
    runs-on: ubuntu-latest
    steps:
    - name: Install trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin $TRIVY_VERSION

    - name: Check trivy version
      run: |
        trivy version

    - name: Scan your image and generate sbom
      run: |
        trivy image ${{ inputs.image }} --format ${{ inputs.format }} --output sbom

    - name: Create cyclonedx
      if: inputs.add-cyclonedx == true
      run: |
        trivy